#!/bin/bash
# drive: attach this project terminal to the pi driver in base_pi.
# Generated by base_pi/.pi/scripts/drive-provision.sh — do not hand-edit.
# Usage: drive [session-name]  (default: __ALIAS__-link)
KEY=__DIR__/.pi-ssh/id_ed25519
IP=$(cat __DIR__/.pi-ssh/basepi-ip 2>/dev/null)
SESS="${1:-__ALIAS__-link}"
exec ssh -i "$KEY" -p 2222 -o StrictHostKeyChecking=no vscode@"$IP" -t "tmux new-session -A -s $SESS"
