#!/bin/bash
# drive: attach this project terminal to the pi driver in base_pi.
# Generated by base_pi/.pi/scripts/drive-provision.sh — do not hand-edit.
# Gives this shell its own agent identity: without it every `pi` started here
# would read base_pi's config and wake up as Ziggy, fighting over one room.
# Inline config wins over the folder file (same mechanism the supervisor uses).
# NOTE: ssh never forwards local env, so the export above is only half the job;
# the ssh command also stamps it into the tmux session on the base_pi side, where
# every new `pi` in that session inherits it. Restart `pi` after re-driving.
export REMOTE_PI_DIRECT_CONFIG='{"agent_name":"__ALIAS__-driver","auto_start_relay":true}'
# Usage: drive [session-name]  (default: __ALIAS__-link)
KEY=__DIR__/.pi-ssh/id_ed25519
IP=$(cat __DIR__/.pi-ssh/basepi-ip 2>/dev/null)
SESS="${1:-__ALIAS__-link}"
exec ssh -i "$KEY" -p 2222 -o StrictHostKeyChecking=no vscode@"$IP" -t "tmux set-environment -t $SESS REMOTE_PI_DIRECT_CONFIG {\"agent_name\":\"__ALIAS__-driver\",\"auto_start_relay\":true} >/dev/null 2>&1; tmux new-session -A -s $SESS"
